---
#
# Base image AWS AMI
#
- hosts: all
  become: yes
  roles:
      # base ami roles
      #
      - { common }
      - { oracle-jdk }
      - { supervisor }
  tasks:
    - name: update all
      yum:
        name: *
        state: latest
