---

- hosts: all      # apply to all hosts
  become: yes     # do everything as root/sudo/dzdo
  vars:
    # project specific variables
    #
    - project_name: 'springboot-app'
    - pkg: 'spring-app-1.1.0'

  roles:
    # springboot-app roles
    #
    - { deploy, pkg_name: {{ pkg }}, rpm: true }

  tasks:
    # custom tasks
    #
    - name: tunning
      lineinfile:
        line: 'tuning here'
        dest: '/path/to/file'
